const carsData = [
    {
        name: "All New Rush",
        type: "SUV",
        image: "src/assets/img/Car5.png",
        isFavorite: false,
        fuelCapacity: "70L",
        transmission: "Manual",
        capacity: 6,
        price: 72,
        discountedPrice: 80,
    },
    {
        name: "CR - V",
        type: "SUV",
        image: "src/assets/img/Car6.png",
        isFavorite: true,
        fuelCapacity: "80L",
        transmission: "Manual",
        capacity: 6,
        price: 80,
    },
    {
        name: "All New Terios",
        type: "SUV",
        image: "src/assets/img/Car7.png",
        isFavorite: false,
        fuelCapacity: "90L",
        transmission: "Manual",
        capacity: 6,
        price: 74,
    },
    {
        name: "MG ZX Exclusive",
        type: "Hatchback",
        image: "src/assets/img/Car9.png",
        isFavorite: true,
        fuelCapacity: "70L",
        transmission: "Manual",
        capacity: 4,
        price: 76,
        discountedPrice: 80,
    },
    {
        name: "All New Rush",
        type: "SUV",
        image: "src/assets/img/Car5.png",
        isFavorite: false,
        fuelCapacity: "70L",
        transmission: "Manual",
        capacity: 6,
        price: 72,
        discountedPrice: 80,
    },
    { 
        name: "CR - V",
        type: "SUV",
        image: "src/assets/img/Car6.png",
        isFavorite: true,
        fuelCapacity: "80L",
        transmission: "Manual",
        capacity: 6,
        price: 80,
    },
    {
        name: "All New Terios",
        type: "SUV",
        image: "src/assets/img/Car7.png",
        isFavorite: false,
        fuelCapacity: "90L",
        transmission: "Manual",
        capacity: 6,
        price: 74,
    },
    {
        name: "All New Terios",
        type: "SUV",
        image: "src/assets/img/Car7.png",
        isFavorite: false,
        fuelCapacity: "90L",
        transmission: "Manual",
        capacity: 6,
        price: 74,
    },
    {
        name: "MG ZX Exclusive",
        type: "Hatchback",
        image: "src/assets/img/Car9.png",
        isFavorite: true,
        fuelCapacity: "70L",
        transmission: "Manual",
        capacity: 4,
        price: 76,
        discountedPrice: 80,
    }
];

export default carsData;