// <auto-generated />
using System;
using CarBookingAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarBookingAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("FuelCapacity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Spaces")
                        .HasColumnType("integer");

                    b.Property<int>("Transmission")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DiscountedPrice = 400m,
                            FuelCapacity = "100L",
                            Img = "src/assets/img/ferrari/Ferrari Purosangue.png",
                            Name = "Ferrari Purosangue",
                            Price = 390m,
                            Spaces = 4,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            DiscountedPrice = 435m,
                            FuelCapacity = "92L",
                            Img = "src/assets/img/ferrari/Ferrari 12Cilindri.png",
                            Name = "Ferrari 12Cilindri",
                            Price = 420m,
                            Spaces = 2,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            DiscountedPrice = 285m,
                            FuelCapacity = "78L",
                            Img = "src/assets/img/ferrari/Ferrari F8 Spider.png",
                            Name = "Ferrari F8 Spider",
                            Price = 275m,
                            Spaces = 2,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            DiscountedPrice = 330m,
                            FuelCapacity = "65L",
                            Img = "src/assets/img/ferrari/Ferrari 296 GTB.png",
                            Name = "Ferrari 296 GTB",
                            Price = 320m,
                            Spaces = 2,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            DiscountedPrice = 290m,
                            FuelCapacity = "78L",
                            Img = "src/assets/img/ferrari/Ferrari F8 Tributo.png",
                            Name = "Ferrari F8 Tributo",
                            Price = 280m,
                            Spaces = 2,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            DiscountedPrice = 2550m,
                            FuelCapacity = "120L",
                            Img = "src/assets/img/ferrari/Ferrari F80.png",
                            Name = "Ferrari F80",
                            Price = 2500m,
                            Spaces = 2,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = 3,
                            DiscountedPrice = 240m,
                            FuelCapacity = "80L",
                            Img = "src/assets/img/ferrari/Ferrari Portofino M.png",
                            Name = "Ferrari Portofino M",
                            Price = 230m,
                            Spaces = 2,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = 4,
                            DiscountedPrice = 230m,
                            FuelCapacity = "80L",
                            Img = "src/assets/img/ferrari/Ferrari Roma.png",
                            Name = "Ferrari Roma",
                            Price = 220m,
                            Spaces = 2,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            DiscountedPrice = 570m,
                            FuelCapacity = "68L",
                            Img = "src/assets/img/ferrari/Ferrari SF90 Spider.png",
                            Name = "Ferrari SF90 Spider",
                            Price = 550m,
                            Spaces = 2,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            DiscountedPrice = 540m,
                            FuelCapacity = "68L",
                            Img = "src/assets/img/ferrari/Ferrari SF90 Stradale.png",
                            Name = "Ferrari SF90 Stradale",
                            Price = 525m,
                            Spaces = 2,
                            Transmission = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
