const recommendationCarsData = [
    {
        name: "Ferrari 296 GTB",
        type: "Sport",
        image: "src/assets/img/ferrari/Ferrari 296 GTB.png",
        isFavorite: false,
        fuelCapacity: "65L",
        transmission: "Automatic",
        capacity: 2,
        price: 320,
        discountedPrice: 330,
    },
    {
        name: "Ferrari F8 Tributo",
        type: "Sport",
        image: "src/assets/img/ferrari/Ferrari F8 Tributo.png",
        isFavorite: false,
        fuelCapacity: "78L",
        transmission: "Automatic",
        capacity: 2,
        price: 280,
        discountedPrice: 290,
    },
    {
        name: "Ferrari F80",
        type: "Supercar",
        image: "src/assets/img/ferrari/Ferrari F80.png",
        isFavorite: false,
        fuelCapacity: "120L",
        transmission: "Automatic",
        capacity: 2,
        price: 2500,
        discountedPrice: 2550,
    },
    {
        name: "Ferrari Portofino M",
        type: "Convertible",
        image: "src/assets/img/ferrari/Ferrari Portofino M.png",
        isFavorite: false,
        fuelCapacity: "80L",
        transmission: "Automatic",
        capacity: 2,
        price: 230,
        discountedPrice: 240,
    },
    {
        name: "Ferrari Roma",
        type: "GrandTouring",
        image: "src/assets/img/ferrari/Ferrari Roma.png",
        isFavorite: false,
        fuelCapacity: "80L",
        transmission: "Automatic",
        capacity: 2,
        price: 220,
        discountedPrice: 230,
    },
    {
        name: "Ferrari SF90 Spider",
        type: "Supercar",
        image: "src/assets/img/ferrari/Ferrari SF90 Spider.png",
        isFavorite: false,
        fuelCapacity: "68L",
        transmission: "Automatic",
        capacity: 2,
        price: 550,
        discountedPrice: 570,
    },
    {
        name: "Ferrari SF90 Stradale",
        type: "Supercar",
        image: "src/assets/img/ferrari/Ferrari SF90 Stradale.png",
        isFavorite: false,
        fuelCapacity: "68L",
        transmission: "Automatic",
        capacity: 2,
        price: 525,
        discountedPrice: 540,
    }
];

export default recommendationCarsData;